Repository prgrms-web-devcourse/Team-5YES-WuMo-FE, pull requests merged in 2023-04, with the labels that each got.

#221 서브타이틀 동적 변경 구현
  index.html
  src/components/party/partyInformation/PartyInformation.tsx
  src/hooks/useDocumentTitle.ts
  src/pages/BestRouteListPage.tsx
  src/pages/InvitationPage.tsx
  src/pages/LandingPage.tsx
  src/pages/LikeRouteListPage.tsx
  src/pages/MainPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/PartyCreatePage.tsx
  src/pages/PartyListPage.tsx
  src/pages/ProfileEditPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/RouteDetailPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
Labels: feature, refactor

#226 구글 애널리틱스 연동
  package-lock.json
  package.json
  src/Router.tsx
  src/main.tsx
  src/utils/RouteChangeTracker.tsx
Labels: feature

#224 프로필 수정 인풋 수정
  src/components/base/input/ControlledInput.tsx
  src/components/base/input/EmailInput.tsx
  src/components/base/input/NicknameInput.tsx
  src/components/profile/profileEdit/ProfileEditForm.tsx
  src/components/profile/profileEdit/ProfileEditImage.tsx
  src/components/userSign/signIn/SignInForm.tsx
  src/components/userSign/signUp/SignUpForm.tsx
  src/types/user.d.ts
Labels: refactor

#227 초대 아이콘 변경
  src/components/party/partyInformation/PartyInformation.tsx
Labels: design

#231 사용금액 input 리팩토링
  src/api/schedules.ts
  src/components/party/schedule/routeComment/placeAmount/PlaceAmountField.tsx
  src/types/schedule.d.ts
Labels: refactor

#235 베스트 루트 목록 제목 변경
  README.md
  src/Router.tsx
  src/api/schedules.ts
  src/components/base/SearchInput.tsx
  src/components/main/BestRouteListPreview.tsx
  src/components/party/schedule/RouteTitle.tsx
  src/components/party/schedule/routeRelease/RouteReleaseChange.tsx
  src/components/routeList/LikeRouteList.tsx
  src/pages/BestRouteListPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/RouteDetailPage.tsx
  src/types/router.d.ts
  src/utils/RedirectRouter.tsx
Labels: feature, refactor

#236 JWT 보안 개선
  src/api/api.ts
  src/api/user.ts
  src/components/base/toast/Toast.tsx
  src/components/base/toast/ToastItem.tsx
  src/components/base/toast/ToastManager.tsx
  src/components/userSign/signIn/SignInForm.tsx
  src/pages/InvitationPage.tsx
  src/pages/NotFoundPage.tsx
  src/types/toast.d.ts
  src/utils/RedirectRouter.tsx
  src/utils/constants/auth.ts
  src/utils/constants/messages.ts
Labels: refactor
