Repository prgrms-web-devcourse/Team-5YES-WuMo-FE, pull requests merged in 2023-02, with the labels that each got.

#5 Router 초기 설정
  src/App.tsx
  src/Router.tsx
  src/pages/.empty
  src/pages/MainPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/index.ts
  src/utils/.empty
  src/utils/routes.ts
Labels: feature

#7 모임페이지 정보 섹션 구현
  .husky/pre-commit
  package-lock.json
  package.json
  src/Router.tsx
  src/components/.empty
  src/components/Party/PartyInformation/PartyInformation.tsx
  src/components/Party/PartyInformation/PartyMenuTabList.tsx
  src/components/Party/PartyInformation/PartyUserList.tsx
  src/main.tsx
  src/pages/PartyAlbumPage.tsx
  src/pages/PartyNoticePage.tsx
  src/pages/PartyPlanPage.tsx
  src/pages/PartySchedulePage.tsx
  src/pages/index.ts
  src/utils/routes.ts
Labels: feature, design

#8 모바일 반응형 레이아웃 세팅
  package-lock.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/components/bottomNavigation/BottomNavigation.tsx
  src/pages/LikeRouteListPage.tsx
  src/pages/PartyCreatePage.tsx
  src/styles/common.tsx
  src/styles/globalStyle.ts
  src/utils/routes.ts
Labels: feature, design

#11 회원가입 페이지 구현
  package-lock.json
  package.json
  src/components/signUp/SignUpForm.tsx
  src/main.tsx
  src/pages/SignUpPage.tsx
  src/types/.empty
  src/types/signup.d.ts
  src/utils/messages.ts
  src/utils/schema.ts
Labels: feature

#13 메인페이지 레이아웃 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/main/BestLouteList.tsx
  src/components/main/TotalPartyNoticeList.tsx
  src/components/main/UserPartyList.tsx
  src/main.tsx
  src/pages/MainPage.tsx
  src/utils/routes.ts
Labels: feature

#16 conflict 버그 수정
  package-lock.json
  package.json
  src/main.tsx
Labels: bug, fix

#18 베스트 여행 루트 목록 페이지 구현
  src/App.tsx
  src/Router.tsx
  src/components/navigation/BackNavigation.tsx
  src/components/navigation/BottomNavigation.tsx
  src/components/route/Route.tsx
  src/pages/BestRouteDetailPage.tsx
  src/pages/BestRouteListPage.tsx
  src/pages/index.ts
  src/styles/common.tsx
  src/types/backNavigation.d.ts
  src/utils/routes.ts
Labels: feature, design

#19 지도 장소 검색 모달 구현
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/Router.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyInformation/PartyMenuTabList.tsx
  src/components/party/partyInformation/PartyUserList.tsx
  src/components/party/place/PlaceListTable.tsx
  src/components/party/place/PlacePreviewMap.tsx
  src/components/party/place/PlaceSearchForm.tsx
  src/components/party/place/PlaceSearchModal.tsx
  src/hooks/useMapPlaces.ts
  src/hooks/useMapScript.ts
  src/main.tsx
  src/pages/PlaceCreatePage.tsx
  src/pages/index.ts
  src/types/place.d.ts
  src/utils/messages.ts
  src/utils/routes.ts
  tsconfig.json
Labels: feature, design

#24 회원가입 페이지 기능 추가
  src/Router.tsx
  src/components/signUp/SignUpForm.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/index.ts
  src/utils/routes.ts
Labels: feature

#27 차크라 Theme 설정
  src/App.tsx
  src/Router.tsx
  src/components/main/BestLouteList.tsx
  src/components/main/UserPartyList.tsx
  src/components/navigation/BottomNavigation.tsx
  src/components/party/partyInformation/PartyMenuTabList.tsx
  src/components/signUp/SignUpForm.tsx
  src/main.tsx
  src/styles/common.tsx
  src/types/navigationItem.d.ts
  src/utils/constants/messages.ts
  src/utils/constants/navigationItem.ts
  src/utils/constants/routes.ts
  src/utils/schema.ts
Labels: refactor

#25 메인 헤더 구현
  public/logo.svg
  src/components/main/MainHeader.tsx
  src/pages/MainPage.tsx
Labels: feature, design

#33 하단 navbar background-color 설정
  src/components/navigation/BottomNavigation.tsx
Labels: design

#31 buttom sheet 모달 구현
  src/components/base/BottomSheet.tsx
  src/components/base/CustomTextarea.tsx
  src/styles/globalStyle.ts
  src/types/bottomSheet.d.ts
Labels: feature

#29 로그인 페이지 구현
  src/components/signIn/SignInForm.tsx
  src/components/signIn/SignInInput.tsx
  src/components/signUp/SignUpForm.tsx
  src/hooks/useLocalStorage.ts
  src/pages/SignInPage.tsx
  src/types/signup.d.ts
  src/types/userSign.d.ts
  src/utils/schema.ts
Labels: feature

#35 로그인 페이지 스타일링
  public/logo-lg.svg
  src/Router.tsx
  src/components/base/LargeLogo.tsx
  src/components/base/SubmitButton.tsx
  src/components/navigation/BottomNavigation.tsx
  src/components/signIn/FindUserInfo.tsx
  src/components/signIn/SignInForm.tsx
  src/components/signIn/SignInInput.tsx
  src/components/signIn/ToSignUp.tsx
  src/pages/SignInPage.tsx
Labels: design

#36 절대경로 설정 변경
  src/components/main/BestLouteList.tsx
  src/components/main/MainHeader.tsx
  src/components/main/UserPartyList.tsx
  src/components/navigation/BackNavigation.tsx
  src/components/navigation/BottomNavigation.tsx
  src/components/party/partyInformation/PartyMenuTabList.tsx
  src/components/party/place/PlaceSearchModal.tsx
  src/components/route/Route.tsx
  src/components/signIn/FindUserInfo.tsx
  src/components/signIn/SignInForm.tsx
  src/components/signIn/ToSignUp.tsx
  src/components/signUp/SignUpForm.tsx
  src/hooks/useMapPlaces.ts
  src/pages/BestRouteListPage.tsx
  src/pages/MainPage.tsx
  src/pages/PlaceCreatePage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/utils/constants/navigationItem.ts
  tsconfig.json
  vite.config.ts
Labels: chore

#43 여행 댓글 피드 페이지 레이아웃 구현
  src/Router.tsx
  src/components/base/FloatingButton.tsx
  src/components/navigation/BottomNavigation.tsx
  src/components/party/schedule/CommentFeedItem.tsx
  src/components/party/schedule/CommentFeedTitle.tsx
  src/components/party/schedule/PlaceAmountField.tsx
  src/components/party/schedule/PlaceCommentFeed.tsx
  src/pages/PartyCommentPage.tsx
  src/pages/PlaceCreatePage.tsx
  src/pages/index.ts
  src/styles/globalStyle.ts
  src/types/floatingButton.d.ts
  src/types/schedule.d.ts
  src/utils/constants/routes.ts
  src/utils/dateTransform.ts
  src/utils/scrollToTop.ts
Labels: feature, design

#42 모임리스트 페이지 마크업, 스타일링
  src/Router.tsx
  src/components/navigation/BackNavigation.tsx
  src/components/party/partyList/PartyList.tsx
  src/components/party/partyList/PartyListCard.tsx
  src/pages/PartyListPage.tsx
  src/pages/PlaceCreatePage.tsx
  src/pages/index.ts
  src/types/party.d.ts
Labels: feature

#50 파티 생성 페이지 구현
  package-lock.json
  package.json
  src/Router.tsx
  src/components/main/BestRouteList.tsx
  src/components/main/MainHeader.tsx
  src/components/main/UserPartyList.tsx
  src/components/navigation/BottomNavigation.tsx
  src/components/party/create/PartyNameModal.tsx
  src/components/party/create/PartyOwnRoleModal.tsx
  src/components/party/create/PartyPeriodModal.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/place/create/PlaceCreateModal.tsx
  src/components/party/place/create/PlaceCreateStepItem.tsx
  src/components/party/place/create/info/DateTimeInput.tsx
  src/components/party/place/create/search/PlacePreviewMap.tsx
  src/components/route/Route.tsx
  src/main.tsx
  src/pages/MainPage.tsx
  src/pages/PartyCreatePage.tsx
  src/pages/PlaceCreatePage.tsx
  src/pages/index.ts
  src/store/.empty
  src/store/recoilPartyState.ts
  src/styles/globalStyle.ts
  src/types/navigationItem.d.ts
  src/types/party.d.ts
  src/types/place.d.ts
  src/utils/constants/navigationItem.ts
  src/utils/constants/party.ts
  src/utils/constants/processStep.tsx
  src/utils/constants/routes.ts
Labels: feature

#52 마이페이지 레이아웃 구현
  src/Router.tsx
  src/components/profile/PartyListGrid.tsx
  src/components/profile/UserProfile.tsx
  src/pages/ProfilePage.tsx
  src/pages/index.ts
  src/utils/constants/navigationItem.ts
  src/utils/constants/routes.ts
Labels: feature
