Repository prgrms-web-devcourse/Team-5YES-WuMo-FE, pull requests merged in 2023-03, with the labels that each got.

#51 파티 계획 탭 레이아웃 구현
  src/Router.tsx
  src/components/party/partyPlan/PlanPlaceList.tsx
  src/components/placeCreate/PlaceCreateModal.tsx
  src/components/placeCreate/category/PlaceCategoryStep.tsx
  src/components/placeCreate/info/DateTimeInput.tsx
  src/components/placeCreate/info/ImageInput.tsx
  src/components/placeCreate/info/PlaceInfoStep.tsx
  src/components/placeCreate/info/PriceInput.tsx
  src/components/placeCreate/info/TextareaInput.tsx
  src/components/placeCreate/search/PlaceList.tsx
  src/components/placeCreate/search/PlacePreviewMap.tsx
  src/components/placeCreate/search/PlaceSearchForm.tsx
  src/components/placeCreate/search/PlaceSearchStep.tsx
  src/main.tsx
  src/pages/PartyPlanPage.tsx
  src/pages/PlacePage.tsx
  src/pages/index.ts
  src/types/place.d.ts
  src/utils/constants/place.ts
  src/utils/constants/processStep.tsx
  src/utils/constants/routes.ts
Labels: feature, design

#55 후보지 상세페이지 레이아웃 구현
  src/components/party/create/PartyOwnRoleModal.tsx
  src/components/party/partyPlan/PlanPlaceList.tsx
  src/components/place/CommentForm.tsx
  src/components/place/PlaceInfoTable.tsx
  src/components/placeCreate/PlaceCreateModal.tsx
  src/components/placeCreate/category/PlaceCategoryStep.tsx
  src/components/placeCreate/info/PlaceInfoStep.tsx
  src/pages/PlaceCreatePage.tsx
  src/pages/PlacePage.tsx
  src/types/place.d.ts
  src/utils/constants/place.tsx
Labels: feature, design

#56 로그인, 회원가입 페이지 레이아웃 수정
  src/components/party/partyList/PartyListCard.tsx
  src/components/signIn/SignInForm.tsx
  src/components/signUp/SignUpForm.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
Labels: design

#58 루트 타임라인 레이아웃 구현
  src/Router.tsx
  src/components/base/ScrollToTop.ts
  src/components/navigation/BackNavigation.tsx
  src/components/navigation/BottomNavigation.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyInformation/PartyMenuTabList.tsx
  src/components/party/partyList/PartyListCard.tsx
  src/components/party/schedule/PlaceCommentFeed.tsx
  src/components/party/schedule/RouteTimeline.tsx
  src/components/party/schedule/RouteTimelineItem.tsx
  src/main.tsx
  src/pages/PartyCommentPage.tsx
  src/pages/PartySchedulePage.tsx
  src/types/schedule.d.ts
  src/utils/constants/navigationItem.ts
Labels: feature, design

#61 후보지 상세페이지 뒤로가기 추가
  src/pages/PlacePage.tsx
Labels: feature, design

#62 관심목록 페이지 구현
  src/App.tsx
  src/components/route/PlaceLocationList.tsx
  src/components/route/Route.tsx
  src/pages/LikeRouteListPage.tsx
  src/styles/globalStyle.ts
  src/types/routeList.d.ts
Labels: feature

#65 앨범 탭 레이아웃 구현
  src/components/party/album/AlbumGird.tsx
  src/pages/PartyAlbumPage.tsx
Labels: feature

#67 베스트 루트 목록 완성 (검색 폼 만들기)
  src/components/navigation/BackNavigation.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyInformation/PartyMenuTabList.tsx
  src/components/party/schedule/CommentFeedTitle.tsx
  src/components/party/schedule/PlaceCommentFeed.tsx
  src/pages/BestRouteDetailPage.tsx
Labels: feature

#69 영수증 모달 구현
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyInformation/receipt/PartyReceipt.tsx
  src/components/party/partyInformation/receipt/PartyReceiptItem.tsx
  src/components/party/partyInformation/receipt/ReceiptTriangle.tsx
  src/components/party/schedule/CommentFeedItem.tsx
  src/components/party/schedule/CommentFeedTitle.tsx
  src/components/party/schedule/RouteTimeline.tsx
  src/components/party/schedule/RouteTimelineItem.tsx
  src/pages/PartySchedulePage.tsx
  src/types/party.d.ts
  src/types/receiptModal.d.ts
  src/types/schedule.d.ts
  src/utils/dateTransform.ts
  src/utils/formatter.ts
Labels: feature, design

#74 Axios Interceptor 추가 & 적용
  src/api/.empty
  src/api/api.ts
  src/components/party/create/PartyOwnRoleModal.tsx
  src/components/signIn/SignInForm.tsx
  src/main.tsx
  src/store/recoilPartyState.ts
  src/types/party.d.ts
Labels: feature

#81 댓글 피드 페이지 레이아웃 수정
  src/components/party/schedule/CommentFeedTitle.tsx
  src/components/party/schedule/PlaceAmountField.tsx
  src/components/party/schedule/PlaceCommentFeed.tsx
  src/components/party/schedule/RouteTimelineItem.tsx
  src/hooks/useScrollEvent.ts
  src/pages/PartyCommentPage.tsx
  src/pages/PlacePage.tsx
  src/types/backNavigation.d.ts
  src/types/schedule.d.ts
  src/utils/constants/place.tsx
Labels: design

#78 회원가입 API 연결
  src/components/signUp/SignUpForm.tsx
  src/utils/constants/messages.ts
  src/utils/schema.ts
Labels: feature

#83 파티 수정 햄버거메뉴 구현
  src/components/navigation/BackNavigation.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyUpdate/PartyUpdate.tsx
  src/pages/BestRouteListPage.tsx
  src/types/backNavigation.d.ts
  src/types/party.d.ts
  src/utils/constants/navigationItem.ts
Labels: feature, design

#85 MoreMenu 컴포넌트 구현
  src/components/base/MoreMenu.tsx
  src/main.tsx
  src/types/moreMenu.d.ts
Labels: feature

#87 404페이지 구현
  public/notfound-logo.svg
  src/Router.tsx
  src/components/base/LargeLogo.tsx
  src/pages/NotFoundPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/index.ts
Labels: feature

#90 메인페이지 레이아웃 수정
  src/Router.tsx
  src/components/main/PartCreateGuide.tsx
  src/components/main/TotalPartyNoticeList.tsx
  src/pages/MainPage.tsx
  src/pages/PartyNoticePage.tsx
  src/pages/index.ts
Labels: feature, design

#91 로그인 API 연결
  src/api/api.ts
  src/components/signIn/SignInForm.tsx
  src/types/tokens.d.ts
Labels: feature

#95 확인 모달 레이아웃 구현
  src/components/base/ConfirmModal.tsx
  src/pages/PartyPlanPage.tsx
  src/types/confirmModal.d.ts
Labels: feature, design

#93 댓글 페이지, 후보지 페이지 moreMenu 연결
  src/components/base/MoreMenu.tsx
  src/components/navigation/BackNavigation.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/schedule/PlaceCommentFeed.tsx
  src/pages/PlacePage.tsx
  src/types/backNavigation.d.ts
  src/types/moreMenu.d.ts
  src/utils/constants/navigationItem.ts
Labels: feature

#94 후보지 등록 상태관리 로직 추가
  src/Router.tsx
  src/components/base/FloatingButton.tsx
  src/components/base/ModalButton.tsx
  src/components/party/create/PartyNameModal.tsx
  src/components/party/create/PartyOwnRoleModal.tsx
  src/components/party/create/PartyPeriodModal.tsx
  src/components/party/partyPlan/PlanPlaceList.tsx
  src/components/party/schedule/PlaceCommentFeed.tsx
  src/components/party/schedule/RouteTimelineItem.tsx
  src/components/place/PlaceInfoTable.tsx
  src/components/place/create/category/PlaceCategoryModal.tsx
  src/components/place/create/information/DateTimeInput.tsx
  src/components/place/create/information/Descriptionnput.tsx
  src/components/place/create/information/ImageInput.tsx
  src/components/place/create/information/PlaceInformationModal.tsx
  src/components/place/create/information/PriceInput.tsx
  src/components/place/create/search/PlaceList.tsx
  src/components/place/create/search/PlacePreviewMap.tsx
  src/components/place/create/search/PlaceSearchForm.tsx
  src/components/place/create/search/PlaceSearchModal.tsx
  src/components/placeCreate/PlaceCreateModal.tsx
  src/components/placeCreate/category/PlaceCategoryStep.tsx
  src/components/placeCreate/info/DateTimeInput.tsx
  src/components/placeCreate/info/PlaceInfoStep.tsx
  src/components/placeCreate/info/PriceInput.tsx
  src/components/placeCreate/info/TextareaInput.tsx
  src/components/placeCreate/search/PlaceList.tsx
  src/components/placeCreate/search/PlaceSearchStep.tsx
  src/hooks/useMapPlaces.ts
  src/pages/PartyPlanPage.tsx
  src/pages/PlaceCreatePage.tsx
  src/pages/PlacePage.tsx
  src/store/recoilPlaceState.ts
  src/types/button.d.ts
  src/types/floatingButton.d.ts
  src/types/place.d.ts
  src/utils/constants/emoji.ts
  src/utils/constants/messages.ts
  src/utils/constants/party.ts
  src/utils/constants/place.tsx
  src/utils/constants/processStep.tsx
  src/utils/formatter.ts
  tsconfig.json
Labels: feature, refactor

#99 프로필 수정 페이지 레이아웃 구현
  src/Router.tsx
  src/components/base/BottomSheet.tsx
  src/components/base/ControlledInput.tsx
  src/components/party/partyList/PartyListGrid.tsx
  src/components/profile/UserProfile.tsx
  src/components/profile/profileEdit/ProfileEditForm.tsx
  src/components/signIn/SignInForm.tsx
  src/pages/ProfileEditPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/index.ts
  src/types/bottomSheet.d.ts
  src/types/place.d.ts
  src/types/user.d.ts
  src/utils/constants/messages.ts
  src/utils/constants/routes.ts
  src/utils/schema.ts
Labels: feature

#100 모임 일정 조회 api 연결
  package-lock.json
  package.json
  src/api/partyInformation.ts
  src/api/schedules.ts
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyInformation/PartyUserList.tsx
  src/components/party/partyInformation/receipt/PartyReceipt.tsx
  src/components/party/schedule/CommentFeedItem.tsx
  src/components/party/schedule/PlaceCommentFeed.tsx
  src/components/party/schedule/RouteTimeline.tsx
  src/components/party/schedule/RouteTimelineItem.tsx
  src/main.tsx
  src/pages/BestRouteDetailPage.tsx
  src/pages/PartySchedulePage.tsx
  src/types/party.d.ts
  src/types/receiptModal.d.ts
  src/types/schedule.d.ts
  src/utils/constants/place.tsx
Labels: feature

#103 지도 마커 아이콘 및 인포윈도우 추가
  src/components/place/create/search/PlacePreviewMap.tsx
  src/pages/PartyPlanPage.tsx
  src/types/place.d.ts
Labels: feature

#106 로딩 컴포넌트 만들기
  src/components/base/Loading.tsx
  src/main.tsx
Labels: feature

#113 로그인 구현 마무리
  src/api/api.ts
  src/api/partyInformation.ts
  src/api/schedules.ts
  src/api/user.ts
  src/components/profile/UserProfile.tsx
  src/components/profile/profileEdit/ProfileEditForm.tsx
  src/components/signIn/SignInForm.tsx
  src/components/signUp/SignUpForm.tsx
Labels: feature

#112 랜딩페이지 생성
  package-lock.json
  public/landing-1.svg
  public/landing-2.svg
  public/landing-3.svg
  src/Router.tsx
  src/components/main/MainHeader.tsx
  src/pages/LandingPage.tsx
  src/pages/index.ts
  src/types/router.d.ts
  src/utils/constants/landingPageItem.ts
  src/utils/constants/redirect.tsx
  src/utils/constants/routes.ts
Labels: feature

#115 댓글 생성 이미지 등록 구현
  src/api/api.ts
  src/api/image.ts
  src/api/schedules.ts
  src/components/base/BottomSheet.tsx
  src/components/base/BottomSheetButton.tsx
  src/components/base/CustomTextarea.tsx
  src/components/party/schedule/CommentCreate.tsx
  src/components/party/schedule/CommentImageInput.tsx
  src/components/party/schedule/PlaceCommentFeed.tsx
  src/components/party/schedule/RouteTimeline.tsx
  src/components/party/schedule/RouteTimelineItem.tsx
  src/components/profile/profileEdit/ProfileEditForm.tsx
  src/pages/PartyCommentPage.tsx
  src/types/bottomSheet.d.ts
  src/types/schedule.d.ts
Labels: feature

#116 메인페이지 api 연결
  src/api/main.ts
  src/components/main/BestRouteList.tsx
  src/components/main/UserPartyList.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/schedule/RouteTimeline.tsx
  src/types/party.d.ts
  src/types/routeList.d.ts
Labels: feature

#128 API 호출 컨벤션 수정
  src/api/api.ts
  src/api/image.ts
  src/api/main.ts
  src/api/schedules.ts
  src/api/user.ts
  src/components/profile/profileEdit/ProfileEditForm.tsx
  src/components/signIn/SignInForm.tsx
  src/components/signUp/SignUpForm.tsx
Labels: refactor

#120 파티원 추방, 파티 수정 모달창 구현
  src/api/api.ts
  src/api/party.ts
  src/api/partyInformation.ts
  src/api/place.ts
  src/api/role.ts
  src/api/schedules.ts
  src/components/navigation/BackNavigation.tsx
  src/components/party/create/PartyNameModal.tsx
  src/components/party/create/PartyOwnRoleModal.tsx
  src/components/party/create/PartyPeriodModal.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyInformation/PartyUserList.tsx
  src/components/party/partyInformation/receipt/PartyReceipt.tsx
  src/components/party/partyUpdate/PartyUpdate.tsx
  src/components/party/update/PartySetting.tsx
  src/components/party/update/PartyUpdateModal.tsx
  src/components/placeCreate/category/PlaceCategoryStep.tsx
  src/components/placeCreate/search/PlaceSearchStep.tsx
  src/store/recoilPartyState.ts
  src/types/navigationItem.d.ts
  src/types/party.d.ts
  src/types/role.d.ts
  src/utils/constants/navigationItem.ts
  src/utils/constants/party.ts
  src/utils/emoji.ts
Labels: feature

#126 모임 리스트 API 연결
  src/api/api.ts
  src/components/party/partyInformation/PartyUserList.tsx
  src/components/party/partyList/PartyList.tsx
  src/components/party/partyList/PartyListCard.tsx
  src/components/profile/UserProfile.tsx
  src/components/signUp/SignUpForm.tsx
  src/types/party.d.ts
Labels: feature

#133 함수 api 폴더로 분리
  src/api/user.ts
  src/components/profile/profileEdit/ProfileEditForm.tsx
  src/components/signIn/SignInForm.tsx
  src/components/signUp/SignUpForm.tsx
Labels: refactor

#134 후보지 사용금액 갱신 api 연결
  src/api/schedules.ts
  src/components/party/schedule/PlaceAmountField.tsx
  src/components/party/schedule/PlaceCommentFeed.tsx
  src/types/schedule.d.ts
Labels: feature

#137 베스트 루트 목록 api 연결
  src/api/schedules.ts
  src/components/navigation/BackNavigation.tsx
  src/components/route/Route.tsx
  src/components/routeList/BestRouteList.tsx
  src/components/routeList/LikeRouteList.tsx
  src/components/routeList/PlaceLocationList.tsx
  src/pages/BestRouteListPage.tsx
  src/pages/LikeRouteListPage.tsx
  src/store/recoilRouteListState.ts
  src/types/routeList.d.ts
Labels: feature

#141 후보지 삭제, 후보지 루트에 추가, 루트에서 후보지 삭제하는 API 연결
  src/api/place.ts
  src/components/base/ConfirmModal.tsx
  src/components/party/partyPlan/PlanPlaceList.tsx
  src/components/party/schedule/RouteReleaseChange.tsx
  src/components/place/create/information/PlaceInformationModal.tsx
  src/components/place/create/search/PlacePreviewMap.tsx
  src/pages/PartyPlanPage.tsx
  src/pages/PlacePage.tsx
  src/types/place.d.ts
  src/utils/constants/place.tsx
  src/utils/constants/routes.ts
Labels: feature, design

#142 내 프로필 관련 API 연결
  src/api/image.ts
  src/api/user.ts
  src/components/main/UserPartyList.tsx
  src/components/party/partyList/PartyListGrid.tsx
  src/components/profile/UserProfile.tsx
  src/components/profile/profileEdit/ProfileEditForm.tsx
  src/types/user.d.ts
  src/utils/schema.ts
Labels: feature

#143 초대링크 기능 구현
  src/Router.tsx
  src/api/party.ts
  src/api/user.ts
  src/components/base/toast/Toast.tsx
  src/components/base/toast/ToastItem.tsx
  src/components/base/toast/ToastManager.tsx
  src/components/main/UserPartyList.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyInformation/PartyUserList.tsx
  src/components/party/schedule/CommentCreate.tsx
  src/components/party/schedule/RouteTimelineItem.tsx
  src/pages/InvitationPage.tsx
  src/pages/MainPage.tsx
  src/pages/PartySchedulePage.tsx
  src/pages/index.ts
  src/types/party.d.ts
  src/types/toast.d.ts
  src/utils/constants/routes.ts
  src/utils/constants/toast.tsx
Labels: feature, refactor

#151 파티 생성, 수정 역할 누락된 api 연결
  src/api/party.ts
  src/api/role.ts
  src/components/party/create/PartyNameModal.tsx
  src/components/party/create/PartyOwnRoleModal.tsx
  src/components/party/create/PartyPeriodModal.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyInformation/PartyUserList.tsx
  src/components/party/partyList/PartyList.tsx
  src/components/party/update/MemberList.tsx
  src/components/party/update/PartySetting.tsx
  src/components/party/update/PartyUpdateModal.tsx
  src/hooks/useButtonDisabled.ts
  src/store/recoilPartyState.ts
  src/styles/globalStyle.ts
  src/types/party.d.ts
  src/types/role.d.ts
Labels: feature

#152 루트 삭제 api 연결
  src/api/schedules.ts
  src/components/main/BestRouteList.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyInformation/PartyUserList.tsx
  src/components/party/schedule/PlaceCommentFeed.tsx
  src/components/party/schedule/RouteReleaseChange.tsx
  src/components/party/schedule/RouteTimeline.tsx
Labels: feature, refactor

#155 관심목록 api 연결
  src/Router.tsx
  src/api/main.ts
  src/api/schedules.ts
  src/components/main/BestRouteListPreview.tsx
  src/components/navigation/BackNavigation.tsx
  src/components/party/schedule/RouteTimeline.tsx
  src/components/routeList/BestRouteMoreList.tsx
  src/components/routeList/LikeRouteList.tsx
  src/pages/BestRouteDetailPage.tsx
  src/pages/BestRouteListPage.tsx
  src/pages/MainPage.tsx
  src/pages/RouteDetailPage.tsx
  src/pages/index.ts
  src/store/recoilRouteListState.ts
  src/types/routeList.d.ts
  src/utils/constants/routes.ts
Labels: feature

#160 이메일 인증 기능 구현
  src/api/user.ts
  src/components/signUp/SignUpForm.tsx
  src/components/signUp/Timer.tsx
  src/main.tsx
  src/utils/constants/messages.ts
Labels: feature

#157 댓글 수정, 삭제 api 연결
  src/api/schedules.ts
  src/components/party/schedule/CommentCreate.tsx
  src/components/party/schedule/CommentDelete.tsx
  src/components/party/schedule/CommentFeedItem.tsx
  src/components/party/schedule/CommentImageInput.tsx
  src/components/party/schedule/CommentUpdate.tsx
  src/components/party/schedule/PlaceCommentFeed.tsx
  src/types/schedule.d.ts
Labels: feature, refactor

#161 영수증 기능 api 연결
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyInformation/PartyUserList.tsx
  src/components/party/partyInformation/receipt/PartyReceipt.tsx
  src/components/party/schedule/RouteReleaseChange.tsx
  src/pages/InvitationPage.tsx
  src/pages/MainPage.tsx
  src/types/party.d.ts
  src/types/receiptModal.d.ts
  src/types/schedule.d.ts
Labels: feature, refactor

#165 메인, 일정 페이지 데이터 없을 때 안내 멘트 설정
  src/api/party.ts
  src/api/schedules.ts
  src/api/user.ts
  src/components/main/BestRouteListItem.tsx
  src/components/main/BestRouteListPreview.tsx
  src/components/main/PartCreateGuide.tsx
  src/components/main/UserPartyList.tsx
  src/components/navigation/BackNavigation.tsx
  src/components/party/partyList/PartyListCard.tsx
  src/components/party/partyList/PartyListGrid.tsx
  src/components/party/schedule/RouteTimeline.tsx
  src/pages/InvitationPage.tsx
  src/types/routeList.d.ts
Labels: refactor, design

#163 후보지 수정 페이지 API 연결, 방문 시간 UI 개선 및 데이터 불일치 이슈 해결
  src/Router.tsx
  src/api/place.ts
  src/components/party/partyPlan/PlanPlaceList.tsx
  src/components/place/create/category/CategoryGrid.tsx
  src/components/place/create/category/PlaceCategoryModal.tsx
  src/components/place/create/information/DateTimeInput.tsx
  src/components/place/create/information/PlaceInformationModal.tsx
  src/components/place/create/information/PriceInput.tsx
  src/components/place/edit/PlaceEditModal.tsx
  src/hooks/useImageUpload.ts
  src/main.tsx
  src/pages/PartyPlanPage.tsx
  src/pages/PlaceCreatePage.tsx
  src/pages/PlaceEditPage.tsx
  src/pages/PlacePage.tsx
  src/store/recoilPlaceState.ts
  src/types/place.d.ts
  src/utils/constants/place.tsx
  src/utils/constants/processStep.tsx
  src/utils/constants/routes.ts
  src/utils/emoji.ts
  src/utils/formatter.ts
Labels: bug, feature, design, fix

#167 후보지 댓글 API 연결
  src/components/place/CommentForm.tsx
  src/components/place/comment/CommentForm.tsx
  src/components/place/comment/CommentList.tsx
  src/hooks/useImageUpload.ts
  src/main.tsx
  src/pages/PlacePage.tsx
  src/types/place.d.ts
  src/utils/constants/messages.ts
  src/utils/formatter.ts
Labels: feature, design

#168 공개된 루트 관심 등록 기능 (좋아요 버튼)
  src/api/route.ts
  src/api/schedules.ts
  src/components/main/BestRouteListItem.tsx
  src/components/navigation/BackNavigation.tsx
  src/components/party/schedule/RouteTimeline.tsx
  src/components/party/schedule/RouteTitle.tsx
  src/components/routeList/BestRouteMoreList.tsx
  src/components/routeList/LikeRouteList.tsx
  src/components/routeList/PlaceLocationList.tsx
  src/hooks/useDebounce.ts
  src/store/recoilRouteListState.ts
  src/types/routeList.d.ts
  src/types/schedule.d.ts
  src/utils/constants/routes.ts
Labels: feature

#170 지도 스크립트 동적 로딩 이슈 해결
  src/components/place/create/search/PlacePreviewMap.tsx
  src/pages/PartyPlanPage.tsx
  src/pages/PlacePage.tsx
Labels: feature, fix

#171 api 에러 처리
  src/api/user.ts
  src/components/base/ControlledInput.tsx
  src/components/party/partyList/PartyListCard.tsx
  src/components/profile/UserProfile.tsx
  src/components/profile/profileEdit/ProfileEditForm.tsx
  src/components/signIn/SignInForm.tsx
  src/components/signUp/SignUpForm.tsx
  src/pages/SignInPage.tsx
Labels: refactor

#175 프로필 수정 페이지 버그 수정
  src/api/user.ts
  src/components/base/ControlledInput.tsx
  src/components/party/partyList/PartyListCard.tsx
  src/components/profile/profileEdit/ProfileEditForm.tsx
  src/components/signIn/SignInForm.tsx
  src/components/signUp/SignUpForm.tsx
Labels: bug, fix

#177 일정 공개 여부 input 필수 값으로 변경
  src/components/base/ConfirmModal.tsx
  src/components/base/MoreMenu.tsx
  src/components/main/UserPartyList.tsx
  src/components/navigation/BackNavigation.tsx
  src/components/party/schedule/PlaceAmountField.tsx
  src/components/party/schedule/RouteCommentFeed.tsx
  src/components/party/schedule/RouteReleaseChange.tsx
  src/components/party/schedule/RouteTimeline.tsx
  src/pages/PartyCommentPage.tsx
  src/types/confirmModal.d.ts
Labels: feature, refactor, design

#178 다른 디바이스 무한로딩 버그 수정
  src/api/api.ts
Labels: bug, fix

#179 후보지 장소 검색결과 렌더링 지연 이슈 해결, 계획 탭 UI 변경
  src/components/party/partyInformation/PartyMenuTabList.tsx
  src/components/party/partyPlan/PlanPlaceList.tsx
  src/components/place/comment/CommentList.tsx
  src/components/place/create/information/PlaceInformationModal.tsx
  src/components/place/create/information/PriceInput.tsx
  src/components/place/create/search/PlaceList.tsx
  src/components/place/create/search/PlacePreviewMap.tsx
  src/components/place/create/search/PlaceSearchForm.tsx
  src/components/place/edit/PlaceEditModal.tsx
  src/hooks/useMapPlaces.ts
  src/hooks/useMapScript.ts
  src/pages/PartyPlanPage.tsx
  src/pages/PlaceCreatePage.tsx
Labels: feature, design, fix

#182 design: 파티리스트 그리드 크기 픽스
  src/components/party/partyList/PartyListGrid.tsx
Labels: design

#184 모임 내 댓글 역할 태그로 변경, ui 수정
  src/components/party/schedule/CommentFeedItem.tsx
  src/components/party/schedule/PlaceAmountField.tsx
Labels: design

#186 alert -> Toast로 수정
  src/components/party/create/PartyOwnRoleModal.tsx
  src/components/party/schedule/PlaceAmountField.tsx
  src/components/party/update/PartySetting.tsx
  src/components/party/update/PartyUpdateModal.tsx
  src/components/place/comment/CommentForm.tsx
  src/components/place/create/category/PlaceCategoryModal.tsx
  src/components/place/create/search/PlaceSearchForm.tsx
  src/components/place/create/search/PlaceSearchModal.tsx
Labels: design

#187 파비콘, 메타 태그 설정
  index.html
  public/favicon.ico
Labels: docs

#188 window.confirm()을 ConfirmModal로 변경
  src/components/party/create/PartyNameModal.tsx
  src/components/party/update/PartyUpdateModal.tsx
  src/components/place/comment/CommentForm.tsx
  src/components/place/create/information/ImageInput.tsx
  src/hooks/useImageSearch.ts
  src/hooks/useImageUpload.ts
  src/pages/InvitationPage.tsx
  src/pages/PlaceCreatePage.tsx
Labels: feature, design

#191 파티원 계정일때 파티수정 로직 변경
  src/api/party.ts
  src/api/role.ts
  src/api/user.ts
  src/components/base/ControlledInput.tsx
  src/components/base/LargeLogo.tsx
  src/components/main/MainHeader.tsx
  src/components/main/PartCreateGuide.tsx
  src/components/main/UserPartyList.tsx
  src/components/navigation/BackNavigation.tsx
  src/components/party/create/PartyNameModal.tsx
  src/components/party/create/PartyOwnRoleModal.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyInformation/PartyUserList.tsx
  src/components/party/partyList/PartyList.tsx
  src/components/party/partyPlan/PlanPlaceList.tsx
  src/components/party/update/MemberList.tsx
  src/components/party/update/PartySetting.tsx
  src/components/party/update/PartyUpdateModal.tsx
  src/components/routeList/BestRouteMoreList.tsx
  src/components/signIn/SignInForm.tsx
  src/components/signUp/SignUpForm.tsx
  src/hooks/useButtonDisabled.ts
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/store/recoilPartyState.ts
  src/styles/globalStyle.ts
  src/types/backNavigation.d.ts
  src/types/party.d.ts
  src/utils/constants/messages.ts
Labels: feature, design

#192 기본이미지 기본 로고로 수정
  src/components/main/BestRouteListItem.tsx
  src/components/main/UserPartyList.tsx
  src/components/party/album/AlbumGird.tsx
  src/components/party/create/PartyNameModal.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyList/PartyListCard.tsx
  src/components/party/partyList/PartyListGrid.tsx
  src/components/party/partyPlan/PlanPlaceList.tsx
  src/components/party/schedule/CommentFeedItem.tsx
  src/components/party/schedule/RouteTimelineItem.tsx
  src/components/party/update/MemberList.tsx
  src/components/party/update/PartySetting.tsx
  src/components/place/comment/CommentList.tsx
  src/components/routeList/BestRouteMoreList.tsx
  src/components/routeList/LikeRouteList.tsx
  src/components/routeList/PlaceLocationList.tsx
  src/pages/PartyAlbumPage.tsx
  src/pages/PlacePage.tsx
  src/pages/index.ts
  src/utils/constants/routes.ts
Labels: design

#193 대용량 이미지 압축
  package-lock.json
  package.json
  src/components/party/create/PartyNameModal.tsx
  src/components/party/schedule/CommentCreate.tsx
  src/components/party/schedule/CommentImageInput.tsx
  src/components/party/schedule/CommentUpdate.tsx
  src/components/place/comment/CommentForm.tsx
  src/components/place/create/information/ImageInput.tsx
  src/components/place/edit/PlaceEditModal.tsx
  src/components/profile/profileEdit/ProfileEditForm.tsx
  src/hooks/useImageUpload.ts
  src/utils/imageCompressor.ts
Labels: feature

#196 댓글 없을 때 가이드 멘트 추가
  src/components/party/schedule/RouteCommentFeed.tsx
Labels: refactor

#199 이미지 로딩 중일 때 스켈레톤 적용
  public/skeleton.svg
  src/components/main/BestRouteListItem.tsx
  src/components/main/BestRouteListPreview.tsx
  src/components/main/UserPartyList.tsx
  src/components/party/create/PartyNameModal.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyInformation/PartyMenuTabList.tsx
  src/components/party/partyList/PartyListCard.tsx
  src/components/party/partyList/PartyListGrid.tsx
  src/components/party/partyPlan/PlanPlaceList.tsx
  src/components/party/schedule/CommentFeedItem.tsx
  src/components/party/schedule/RouteCommentFeed.tsx
  src/components/party/schedule/RouteTimelineItem.tsx
  src/components/routeList/BestRouteMoreList.tsx
  src/components/routeList/LikeRouteList.tsx
  src/components/routeList/PlaceLocationList.tsx
  src/pages/LandingPage.tsx
  src/pages/PlacePage.tsx
Labels: design, fix

#202 사파리에서 링크 공유 안되는 문제 해결
  src/components/party/partyInformation/InvitationCodeModal.tsx
  src/components/party/partyInformation/PartyInformation.tsx
  src/types/party.d.ts
Labels: feature, fix

#204 후보지 댓글 이미지 수정 에러 해결
  src/components/party/schedule/CommentCreate.tsx
  src/components/place/comment/CommentForm.tsx
  src/components/place/comment/CommentList.tsx
Labels: feature, fix

#205 후보지 방문예정일 범위 제한
  src/components/place/create/information/DateTimeInput.tsx
  src/components/place/create/information/PlaceInformationModal.tsx
  src/pages/PlaceCreatePage.tsx
  src/styles/globalStyle.ts
  src/types/place.d.ts
  src/utils/constants/processStep.tsx
Labels: feature, fix

#212 후보지 장소 검색 결과 렌더링 지연 이슈 해결
  src/components/place/create/search/PlaceSearchForm.tsx
  src/hooks/useImageSearch.ts
  src/hooks/useMapPlaces.ts
  src/hooks/useMapScript.ts
Labels: bug

#214 비밀번호 @ 버그 수정
  src/components/signIn/ToSignUp.tsx
  src/components/userSign/ToOtherSign.tsx
  src/components/userSign/signIn/FindUserInfo.tsx
  src/components/userSign/signIn/SignInForm.tsx
  src/components/userSign/signIn/SignInInput.tsx
  src/components/userSign/signUp/SignUpForm.tsx
  src/components/userSign/signUp/Timer.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/utils/schema.ts
Labels: bug, refactor, fix

#216 일정 없을 때 영수증 버튼 반응 없는 문제 해결
  src/components/party/partyInformation/PartyInformation.tsx
  src/components/party/partyInformation/receipt/PartyReceipt.tsx
  src/components/party/schedule/RouteTimeline.tsx
  src/components/party/schedule/routeComment/CommentCreate.tsx
  src/components/party/schedule/routeComment/CommentDelete.tsx
  src/components/party/schedule/routeComment/CommentFeedItem.tsx
  src/components/party/schedule/routeComment/CommentFeedTitle.tsx
  src/components/party/schedule/routeComment/CommentImageInput.tsx
  src/components/party/schedule/routeComment/CommentUpdate.tsx
  src/components/party/schedule/routeComment/RouteCommentFeed.tsx
  src/components/party/schedule/routeComment/placeAmount/PlaceAmountField.tsx
  src/components/party/schedule/routeRelease/RouteReleaseChange.tsx
  src/pages/PartyCommentPage.tsx
  src/types/receiptModal.d.ts
Labels: refactor, fix

#217 회원가입 폼 리팩토링
  src/api/user.ts
  src/components/base/ControlledInput.tsx
  src/components/userSign/signIn/SignInInput.tsx
  src/components/userSign/signUp/EmailInput.tsx
  src/components/userSign/signUp/NicknameInput.tsx
  src/components/userSign/signUp/SignUpForm.tsx
Labels: refactor, fix
